name: Echo workflow

on:
  workflow_dispatch:

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo hello
        run: |
          echo "Running a simple script"
          echo "Current date and time: $(date)"
          echo "List of files in the repository:"
          ls -la